version: "3"

services:
  postgrest-db:
    image: postgres:13
    ports:
      - 3201:5432
    networks:
      - grafana
    volumes:
      - ./sql/init/:/docker-entrypoint-initdb.d
      - ./postgres:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: bE7RYgKdiJtTQNluW0q4W5e0xhCGr8ze

  postgrest:
    image: postgrest/postgrest:v8.0.0
    networks:
      - grafana
    environment:
      PGRST_DB_URI: postgres://app_user:bE7RYgKdiJtTQNluW0q4W5e0xhCGr8ze@postgrest-db:5432/app_db
      PGRST_DB_SCHEMA: api
      PGRST_DB_ANON_ROLE: web_anon
      PGRST_SERVER_PROXY_URI: http://localhost:3202
      PGRST_SERVER_PORT: 3202
      PGRST_JWT_SECRET: eNciuvAC1WzJfWqkj1l9oDEYFOoYvHeqoklk
    depends_on:
      - postgrest-db

  nginx:
    image: nginx:1.21.3-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 3203:8080
    networks:
      - grafana
    depends_on:
      - postgrest

networks:
  grafana:
    external: true
    name: grafana
